#
# VanishNoPacket
#   A fine choice of invisibility for the discerning server administrator.
#   http://www.kitteh.org
#
#
#  Below is a list of settings with some description
#
fakeannounce:
    automaticforsilentjoin: false
    join: '%p joined the game.'
    quit: '%p left the game.'
hooks:
    essentials: false
    dynmap: false
    JSONAPI: false
enableColoration: false
spoutcraft:
    enable: false
updates:
    check: true
permtest:
    enable: false