name: VanishNoPacket
main: to.joe.vanish.VanishPlugin
version: 1.3.3
website: http://forums.joe.to
depend: [Spout]
author: mbaxter
description: Vanish by filtering packets using Spout
commands:
  vanish:
    description: poof
    usage: |
      /vanish
      /vanish check
permissions:
  vanish.vanish:
    default: op
    description: |
      Allows player to vanish. 
      REALLY should give players with this access to vanish.see
  vanish.see:
    default: op
    description: Allows player to see vanished players
  vanish.nopickup:
    description: If true player can pick up items when vanished
  vanish.nofollow:
    description: If true mobs do not follow player when vanished
  vanish.preventincomingdamage:
    description: Prevent being harmed by things around you while vanished
  vanish.preventoutgoingdamage:
    description: Prevent accidentally hurting stuff while vanished
  vanish.silentjoin:
    description: Join silently. Announce on toggling vanish off
  vanish.standard:
    description: Can vanish, see vanished, no pickup when vanished
    children:
      vanish.see: true
      vanish.vanish: true
      vanish.nopickup: true
      vanish.nofollow: true
      vanish.preventincomingdamage: true
      vanish.preventoutgoingdamage: true