name: VanishNoPacket
main: to.joe.vanish.VanishPlugin
version: 1.7alpha
website: http://forums.joe.to
depend: [Spout]
softdepend: [Essentials,dynmap,JSONAPI]
author: mbaxter
description: Vanish by filtering packets using Spout
commands:
  vanish:
    description: poof
    usage: /vanish
    aliases: [v,np,nf,ni]
permissions:
  vanish.vanish:
    default: op
    description: |
      Allows player to vanish. 
      REALLY should give players with this access to vanish.see
  vanish.see:
    default: op
    description: Allows player to see vanished players
  vanish.statusupdates:
    description: Informed about players changing status
    default: op
  vanish.nopickup:
    default: false
    description: If true player can pick up items when vanished
  vanish.nofollow:
    default: false
    description: If true mobs do not follow player when vanished
  vanish.notrample:
    default: false
    description: If true player does not trample crops
  vanish.nointeract:
    default: false
    description: If true player cannot press buttons, open doors, activate pressure pads etc
  vanish.preventincomingdamage:
    default: false
    description: Prevent being harmed by things around you while vanished
  vanish.preventoutgoingdamage:
    default: false
    description: Prevent accidentally hurting stuff while vanished
  vanish.preventdamage:
    default: false
    description: Prevent damage both ways
    children:
      vanish.preventoutgoingdamage: true
      vanish.preventincomingdamage: true
  vanish.silentjoin:
    default: false
    description: Join silently. Announce on toggling vanish off
  vanish.silentquit:
    default: false
    description: ALWAYS quit silently. 
  vanish.toggle.see:
    default: false
    description: Toggle seeing other vanished players
  vanish.toggle.nopickup:
    default: false
    description: Toggle pickup ability
  vanish.toggle.nofollow:
    default: false
    description: Toggle mob aggro
  vanish.toggle.nointeract:
    default: false
    description: Toggle interaction ability (doors, pressurepads, buttons, etc)
  vanish.toggle.damageout:
    default: false
    description: Toggle outgoing damage
  vanish.toggle.damagein:
    default: false
    description: Toggle incoming damage
  vanish.toggle.damage:
    default: false
    description: Toggle both damage in and out
    children:
      vanish.toggle.damageout: true
      vanish.toggle.damagein: true
  vanish.toggle.all:
    default: false
    description: Allows user to toggle all their settings ingame
    children:
      vanish.toggle.see: true
      vanish.toggle.nopickup: true
      vanish.toggle.nofollow: true
      vanish.toggle.damage: true
      vanish.toggle.nointeract: true
  vanish.fakeannounce:
    default: false
    description: Fake joining/leaving
  vanish.adminalerts:
    default: op
    description: Receive alerts about updates and such
  vanish.permtest.self:
    default: true
    description: If PermTest is enabled, be able to use it on yourself
  vanish.permtest.other:
    default: op
    description: If PermTest is enabled, be able to use it on others
  vanish.permtest.all:
    default: op
    description: If PermTest is enabled, be able to use on self and others
    children:
      vanish.permtest.self: true
      vanish.permtest.other: true
  vanish.hooks.dynmap.alwayshidden:
    default: false
    description: Always hide from dynmap
  vanish.standard:
    description: Can vanish, see vanished, no pickup when vanished
    default: false
    children:
      vanish.see: true
      vanish.vanish: true
      vanish.nopickup: true
      vanish.nofollow: true
      vanish.notrample: true
      vanish.nointeract: true
      vanish.fakeannounce: true
      vanish.preventdamage: true
      vanish.statusupdates: true
      vanish.adminalerts: true
  vanish.*:
    description: Oh god everything.
    default: false
    children:
      vanish.standard: true
      vanish.silentjoin: true
      vanish.silentquit: true
      vanish.toggle.all: true
      vanish.hooks.dynmap.alwayshidden: true
      vanish.permtest.all: true